---
- name: issuing commands predictably with win_command
  hosts: windows       # name of the group we want to run against
  #connection: winrm   # we already mapped this in our inventory
  gather_facts: false

  tasks:
    - name: save the result of 'whoami' in 'results'
      ansible.windows.win_command: whoami
      register: results

    - name: save the result of 'ipconfig' in 'results1'
      ansible.windows.win_command: ipconfig
      register: results1

    - name: display the results
      ansible.builtin.debug:
        var: results1
    
    - name: display the results
      ansible.builtin.debug:
        var: results
